# Generated by Django 3.1.2 on 2022-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtelMain',
            fields=[
                ('atelID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ATel ID')),
            ],
        ),
        migrations.CreateModel(
            name='AtelSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AtelSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcra', models.FloatField(verbose_name='R.A. of the source')),
                ('srcdec', models.FloatField(verbose_name='Decl. of the source')),
                ('atelID', models.ManyToManyField(to='atel.AtelMain')),
            ],
        ),
        migrations.AddField(
            model_name='atelmain',
            name='atelSub',
            field=models.ManyToManyField(to='atel.AtelSub'),
        ),
    ]
