# Generated by Django 3.1.2 on 2022-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelsource',
            name='taskname',
            field=models.CharField(default='testtask', max_length=200),
            preserve_default=False,
        ),
    ]
