# Generated by Django 3.1.2 on 2022-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200)),
                ('taskdate', models.DateTimeField(verbose_name='Date task was submitted')),
                ('srcra', models.FloatField(verbose_name='R.A. of the source')),
                ('srcdec', models.FloatField(verbose_name='Decl. of the source')),
                ('fileExist', models.BooleanField(verbose_name='Whether the file is still existed')),
            ],
        ),
    ]
